---

# Gather facts and check connectivity
- hosts: all
  gather_facts: False
  become: true
  
  tasks:
  - name: Disable timers for unattended upgrade, so that none will be triggered by the `date -s` call.
    raw: systemctl disable --now {{item}}
    with_items:
      - 'apt-daily.timer'
      - 'apt-daily-upgrade.timer'
  
  - name: Reload systemctl daemon to apply the new changes
    raw: systemctl daemon-reload
  
  - name: Wait for any possibly running unattended upgrade to finish
    raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
  
  - name: Purge unattended upgrades
    raw: apt-get -y purge unattended-upgrades    
  
  - name: Update apt cache
    raw: apt-get -y update

  - name: install python 2
    raw: until ping -c1 www.google.com &>/dev/null; do :; done; test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
#    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all

- import_playbook: set_facts.yml
- import_playbook: common.yml
- import_playbook: loadbalancer.yml
#- import_playbook: appserver.yml
#- import_playbook: sqlserver.yml

